### ISSUE TITLE
Webpack Error: Can't resolve './src' in '/opt/app/assets'

### ISSUE THREAD

**Issue by KristerV** [bitwalker/alpine-elixir-phoenix#41]
My Dockerfile doesn't build. It did the first time when I had locally installed all dependencies (when Mix asked upon creating a new project), but a clean clone of the code doesn't run it.

```
ERROR in Entry module not found: Error: Can't resolve './src' in '/opt/app/assets'
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development' returned a non-zero code: 2
```

Here's my dockerfile:

```Dockerfile
FROM bitwalker/alpine-elixir-phoenix:latest

# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

# Cache npm deps
ADD assets/package.json assets/
RUN cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development

# Add rest of the app
ADD . .

# USER default
CMD ["mix", "do", "ecto.migrate,", "phx.server"]
```

And docker-compose.yml

```yml
version: "3"
services:
  webapp:
    build:
      context: .
    depends_on:
      - database
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_USER: postgres
      DB_PASS: izmusekr
      DB_HOST: database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: izmusekr
```

I tried all commands separately at one point and made sure that it's definitely the webpack command that is creating the error (not `npm install`). Also the project compiles fine on my local machine without docker.

I tried to  find the `./src` folder in my local compiled project (non-docker) and I could only find them under either `./deps` or `assets/node_modules`. So I'm not sure why webpack is looking for something in the HOME dir in the first place.

**Comment by KristerV** [comment]
Okay. I'm going to close this issue as I've got my answer. I'll post my Dockerfile here for anyone googling into here.

```Dockerfile
# https://github.com/bitwalker/alpine-elixir-phoenix
FROM bitwalker/alpine-elixir-phoenix:latest

# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

# Cache npm deps and static files
ADD assets/ assets/
RUN cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development

# USER default

CMD ["mix", "do", "ecto.migrate,", "phx.server"]
```

And the docker-compose.yml
```yml
version: "3"
services:
  webapp:
    build: .
    depends_on:
      - database
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_USER: postgres
      DB_PASS: pass
      DB_HOST: database
    volumes:
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./test:/opt/app/test
      - ./assets/css:/opt/app/assets/css
      - ./assets/js:/opt/app/assets/js
      - ./assets/static:/opt/app/assets/static
      - ./_build:/opt/app/_build               # Cache compilations
      - ./.elixir_ls:/opt/app/.elixir_ls       # Cache compilations
      - ./deps:/opt/app/deps                   # Cache compilations

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
```
